
name: Image Scanning in CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install npm
        uses: npm install   

      - name: build Docker image
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USER_NAME}} --password-stdin
          echo "logged in successfully"