
name: Image Scanning in CI/CD


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
        

jobs:
  image_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build image
        run: docker build -t bharatmali1704/day2:latest . 

      - name: Trivy scanning plugin
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "bharatmali1704/day2:latest"
          format: "table"
          exit-code: 0
          severity: "CRITICAL, HIGH"

      - name: Generate Trivy report 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "bharatmali1704/day2:latest"
          format: "json"
          output: "trivy-report.json"
          continue-on-error: true

      - name: Upload Report as Artifact     
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.json
      
      # - name: Alert through Slack
      #   if: failure()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "⚠️ Security Alert! Trivy found vulnerabilities in Docker image."
      #     SLACK_COLOR: "#ff0000"
